version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: devdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data/pgdata
  web:
    # Intentionally left blank
